//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_01.Models.DomainModel.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int Pictureid { get; set; }
        public byte[] Picture1 { get; set; }
        public Nullable<int> Productid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
